# Generated by Django 3.2.6 on 2021-12-01 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('camp_name', models.CharField(max_length=200, null=True)),
                ('item_name_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='To_Donate',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.requests')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('donar_name', models.CharField(max_length=200, null=True)),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('doanted', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.to_donate')),
            ],
        ),
    ]
